import { useRef, useState } from "react";
import ClothArticle from "./ClothArticle";
import { Link } from "react-router";
const Slider = ({ list }) => {
  // you need to useState buddy boy!
  const myRef = useRef(null);
  const [translateX, setTranslateX] = useState(0);
  const slideClothes = () => {
    // handle myRef
    console.log(myRef);
    //index += 4;
    //myRef.current.className =`-translate-x-${index} flex overflow-hidden`;
    //myRef.current.className =`-translate-x-70 flex overflow-hidden`;

    setTranslateX(translateX - 200);
  };

  return (
    <section>
      <div className="overflow-hidden">
        <h2 className="text-center text-black text-3xl mt-10 mb-10 tracking-wide font-extrabold">
          NEW ARRIVALS
        </h2>
        <div
          ref={myRef}
          className="flex w-1200"
          style={{
            transform: `translateX(${translateX}px)`,
            transition: "transform 0.3s ease-in-out",
          }}
        >
          {list.map((item, index) => {
            return (
              <Link key={item.id} to={`/projects/shop/home/${item.id}`}>
                <ClothArticle item={item} key={index} />{" "}
              </Link>
            );
          })}
        </div>
      </div>
      <button onClick={slideClothes}>Click me!</button>
    </section>

    // overflow-x-scroll is another solution...
    /*
        <section>
            <div className='overflow-hidden'>
                <h2 
                  className='text-center text-black text-3xl mt-10 tracking-wide font-extrabold' 
                >NEW ARRIVALS
                </h2>
            <div
                ref={myRef}
                className='flex'
                style={{transform: `translateX(${translateX}px)`,
                transition: 'transform 0.3s ease-in-out'}}
            >
                <img 
                    className='w-100 h-100 p-10'
                    src='http://localhost:5173/src/assets/images/tie1.jpg'
                />
                <img 
                    className='w-100 h-100 p-10'
                    src='http://localhost:5173/src/assets/images/blacktee1.png'
                />
                <img 
                    className='w-100 h-100 p-10'
                    src='http://localhost:5173/src/assets/images/jeans1.jpg'
                />
                <img 
                    className='w-100 h-100 p-10'
                    src='http://localhost:5173/src/assets/images/scarf1.jpg'
                />
                <img 
                    className='w-100 h-100 p-10'
                    src='http://localhost:5173/src/assets/images/blacktee1.png'
                />
                <img 
                    className='w-100 h-100 p-10'
                    src='http://localhost:5173/src/assets/images/blacktee1.png'
                />
            </div>
            </div>
            <button
                onClick={slideClothes}
            >Click me!</button>
        </section>
        */
  );
};

//style={{transform: `translateX(${translateX}px)`,
//transition: 'transform 0.3s ease-in-out'}}

/*

code generated by Google AI

<div class="card-slider-container">
  <button class="prev-button">Previous</button>
  <div class="card-slider">
    <div class="card">Card 1</div>
    <div class="card">Card 2</div>
    <div class="card">Card 3</div>
    <div class="card">Card 4</div>
    <div class="card">Card 5</div>
  </div>
  <button class="next-button">Next</button>
</div>


**********************
.card-slider-container {
  position: relative;
  width: 80%;
  margin: 20px auto;
  overflow: hidden;
}

.card-slider {
  display: flex;
  transition: transform 0.5s ease-in-out;
}

.card {
  min-width: 200px;
  height: 150px;
  margin: 10px;
  background-color: #f0f0f0;
  border: 1px solid #ccc;
  text-align: center;
  line-height: 150px;
}

.prev-button,
.next-button {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  background-color: #ddd;
  border: none;
  padding: 10px;
  cursor: pointer;
}

.prev-button {
  left: 10px;
}

.next-button {
  right: 10px;
}




*********
const slider = document.querySelector('.card-slider');
const cards = document.querySelectorAll('.card');
const prevButton = document.querySelector('.prev-button');
const nextButton = document.querySelector('.next-button');

let currentIndex = 0;
const cardWidth = cards[0].offsetWidth + 20; // Include margin

prevButton.addEventListener('click', () => {
  currentIndex = Math.max(currentIndex - 1, 0);
  updateSlider();
});

nextButton.addEventListener('click', () => {
  currentIndex = Math.min(currentIndex + 1, cards.length - 1);
  updateSlider();
});

function updateSlider() {
  slider.style.transform = `translateX(-${currentIndex * cardWidth}px)`;
}

*/

export default Slider;
